; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:4d_systems_esp32s3_gen4_r8n16]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
lib_deps = 
	adafruit/Adafruit MCP23017 Arduino Library@^2.3.2
	adafruit/Adafruit ADXL375@^1.1.2
	adafruit/Adafruit MPL3115A2 Library@^2.1.2
	finani/ICM42688@^1.1.0
	robtillaart/MS5611@^0.5.1
	C:\Users\jason\Google Drive\Raketenbauteam\AG Elektronik\ARCHER\EAGLE v1.2.1\EAGLE v1.2.1\lib\SparkFun_KX13X_Arduino_Library